export const GET_BRANDS = 'GET_BRANDS'
export const GET_TRADE_PAVILIONS = 'GET_TRADE_PAVILIONS'
export const GET_ITEMS = 'GET_ITEMS'
export const SET_CURRENT_TRADE_PAVILIONS = 'SET_CURRENT_TRADE_PAVILIONS'